### ISSUE TITLE
There's a couple problems with this

### ISSUE THREAD

**Issue by NVB9ALT** [Spice9/Geofs-Multiliveries#208]
1. Console injection doesn't work (await function not valid in this use case or something)
2. FIX YOUR UI. The Kolos26 Livery Selector is MUCH, MUCH BETTER because of the fact that it doesn't just append liveries to the aircraft menu. This is nonsensical as this makes the liveries look like addon aircraft, and you also have to scroll up to select the aircraft then down to select the livery. Just add a dropdown in the Options panel that displays all liveries that can be applied to the current aircraft (which would also make it compatible with other UI-based addons like the Challenges Addon). Only then is it at all better than Kolos26's Livery Selector. Until then I'm going to voice strong disapproval of your shameless advertising of your crappy addon in an aircraft's texture file lol. You're getting way too many users through that - there's no way any of us who have better addons can compete and it makes me positively FRUSTRATED with you guys.

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/191892267-f10eb238-8dc4-41f0-8fe7-93da2650c322.png)
wdym it works fine..  

the kolos livery selector's UI is better and I'm not great at coding JS and during the early stages of code I just had to settle for an improper UI like this then Ariakm came and reformatted the code which came with multiplayer . I'm sorry but because of my poor knowledge on coding this basically what I could do. Also I wasnt in any discord server when the addon was released so the only was I could get some reach was through that advert on the max8 cockpit and my yt channel at that time had only 10 subs... also a youtuber  A.I. was helpful in getting more reach ( heres his channel https://www.youtube.com/c/AI-1111) and it was also shared a lot on discord. I dont really mind if you do a similar way of getting more reach...

**Comment by Ariakim-Taiyo** [comment]
I've been considering creating a proper UI for this for quite some time, I've just been too busy recently.

**Comment by NVB9ALT** [comment]
Ok so is it just my bookmarklet console then?
![Screenshot 2022-09-23 9 30 45 AM](https://user-images.githubusercontent.com/102188956/192008946-537e0bfc-3e42-45e5-90bb-97b0edcc80f2.png)

**Comment by Ariakim-Taiyo** [comment]
> Ok so is it just my bookmarklet console then? ![Screenshot 2022-09-23 9 30 45 AM](https://user-images.githubusercontent.com/102188956/192008946-537e0bfc-3e42-45e5-90bb-97b0edcc80f2.png)

Yes. Bookmarklet consoles are not supported.

**Comment by kolos26** [comment]
> ![image](https://user-images.githubusercontent.com/105491758/191892267-f10eb238-8dc4-41f0-8fe7-93da2650c322.png) wdym it works fine..
> 
> the kolos livery selector's UI is better and I'm not great at coding JS and during the early stages of code I just had to settle for an improper UI like this then Ariakm came and reformatted the code which came with multiplayer . I'm sorry but because of my poor knowledge on coding this basically what I could do. Also I wasnt in any discord server when the addon was released so the only was I could get some reach was through that advert on the max8 cockpit and my yt channel at that time had only 10 subs... also a youtuber A.I. was helpful in getting more reach ( heres his channel https://www.youtube.com/c/AI-1111) and it was also shared a lot on discord. I dont really mind if you do a similar way of getting more reach...

Dear @Spice9!

I really don't want to have conflicts around my project, my goal was only to have all the liveries together, to make it easier to use. If you are ok with that, we can develop [liverySelector](https://github.com/kolos26/GEOFS-LiverySelector) together, because I'm mostly in programing, but your liveries are much nicer than mines, and you are well known around GeoFS while I only have five liveries, and no airplanes (yet).

Thanks for this project, without that I would never have started developing liveries to GeoFS.

Kind regards,
Kolos26

**Comment by Spice9** [comment]
> > ![image](https://user-images.githubusercontent.com/105491758/191892267-f10eb238-8dc4-41f0-8fe7-93da2650c322.png) wdym it works fine..
> > the kolos livery selector's UI is better and I'm not great at coding JS and during the early stages of code I just had to settle for an improper UI like this then Ariakm came and reformatted the code which came with multiplayer . I'm sorry but because of my poor knowledge on coding this basically what I could do. Also I wasnt in any discord server when the addon was released so the only was I could get some reach was through that advert on the max8 cockpit and my yt channel at that time had only 10 subs... also a youtuber A.I. was helpful in getting more reach ( heres his channel https://www.youtube.com/c/AI-1111) and it was also shared a lot on discord. I dont really mind if you do a similar way of getting more reach...
> 
> Dear @Spice9!
> 
> I really don't want to have conflicts around my project, my goal was only to have all the liveries together, to make it easier to use. If you are ok with that, we can develop [liverySelector](https://github.com/kolos26/GEOFS-LiverySelector) together, because I'm mostly in programing, but your liveries are much nicer than mines, and you are well known around GeoFS while I only have five liveries, and no airplanes (yet).
> 
> Thanks for this project, without that I would never have started developing liveries to GeoFS.
> 
> Kind regards, Kolos26

 I dont have any problem with your addon using my liveries I am totally fine with your addon and its great. I wont really mind doing collab especially now a days I getting much limited time to focus on this addon and many people have been submitting liveries...  You can join the ML discord server https://discord.gg/bAGQt9WCqk or just DM me on Spice9#6426 for more discussions on a collab .
