### ISSUE TITLE
Making sure all users don't have to manually update their copies of the addon

### ISSUE THREAD

**Issue by NVB9ALT** [Spice9/Geofs-Multiliveries#209]
On my Realism Pack I have a setup that makes sure that users of the addon don't have to update their copies manually - the bookmarklet just calls the latest version of main.js. I'd advise doing the same for Multiliveries since it's so popular, if you haven't already. I do realize, however, that the very large number of people _already_ using Multiliveries means that if you can sort that out with no changes to, say, the Tampermonkey code or whatever, then that's even better. Now, I'm no expert on this addon so correct me if I've got something terribly wrong.
(This is mostly just relevant for the addition of new features or changing links.)

**Comment by Ariakim-Taiyo** [comment]
Generally the addon is pretty plug and play, and all the livery links are referenced to a json file hosted here, so that we don't have to distribute new copies every time we add a livery. We rarely make an update that requires a new install, so old versions still work even if they're way behind the current one. We mostly just push bug fixes and such.

**Comment by Aper583** [comment]
LOL

**Comment by BlueWacki** [comment]
That's rude! Aper583
