### ISSUE TITLE
TUIfly "Haribo GoldbAIR" 737-800 livery

### ISSUE THREAD

**Issue by BChang-3d** [Spice9/Geofs-Multiliveries#221]
I am not lying. this is actually a thing
![image](https://user-images.githubusercontent.com/114553146/198192198-1ef4fd3e-b4cf-4531-86bb-acaec4736185.png)

_________________________________________________________________

Livery:
https://ibb.co/vQbpnS4

--__________________________________________________________________

Please tell me if the livery needs anything and please update me on the status of the upload. THX!!! :)

**Comment by BChang-3d** [comment]
Hello? spice, are you planning to update the code to include these anytime soon?

**Comment by BChang-3d** [comment]
![TUIfly GoldbAIR 737-800 livery](https://user-images.githubusercontent.com/114553146/198713888-567c82c3-e1bc-4287-8606-4bde3110bbe7.jpg)

**Comment by bajushd** [comment]
**From spice9**  "As some of you might know, I had an exam 1-2 weeks ago it wasn't the final one though. While I did have some mediocre grades for subjects other than maths it is an alarming situation for me as I'm not able to focus on my studies well and I'm in an online coaching for entrance exam as well, handling all these things is not giving me enough time to focus on geofs and other stuff. My parents are dissapointed with the borderline grade in maths so it is time I take a break for 2 months so that I could study well for the next term exam"

**Comment by BChang-3d** [comment]
so bajushd, are you gonna take over?

**Comment by bajushd** [comment]
sorry i can't add because i'm not a contributor

**Comment by bajushd** [comment]
How about you join the Multiliveries server on Discord

**Comment by BChang-3d** [comment]
ok i did

**Comment by bajushd** [comment]
ok, I've seen you join
