### ISSUE TITLE
How do the developers add liveries?

### ISSUE THREAD

**Issue by thedolphinsfan1** [Spice9/Geofs-Multiliveries#270]
I am considering creating a fork so I can add some of my own liveries. However, I need guidance on how to add them. Thank you.

**Comment by Ariakim-Taiyo** [comment]
Our liveries.json file contains all of the texture links and other metadata used by the addon.
You can find it at https://github.com/Spice9/Geofs-Multiliveries/blob/main/dependencies/liveries.json

You can look at the example in the readme to see how it is constructed for PBR liveries.

Alternatively, you can join the discord and submit your liveries there so that our maintenance team can add them officially (assuming the livery follows the guidelines).
